apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins-blueocean
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 8080
      nodePort: 31400