apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-blueocean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-blueocean
  template:
    metadata:
      labels:
        app: jenkins-blueocean
    spec:
      containers:
        - name: jenkins-blueocean
          image: devopsjourney1/jenkins-blueocean:2.332.3-1
          env:
            - name: DOCKER_HOST
              value: tcp://docker:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            - name: jenkins-docker-certs
              mountPath: /certs/client
              readOnly: true
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data-pvc
        - name: jenkins-docker-certs
          persistentVolumeClaim:
            claimName: jenkins-docker-certs-pvc
