apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/auto-create: "true"
    argocd-image-updater.argoproj.io/auto-update: "true"
    argocd-image-updater.argoproj.io/image-list: example=docker.io/ruthvik2424/demoproject
    argocd-image-updater.argoproj.io/example.update-strategy: latest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com:ruthvik2424/devops_project.git
    targetRevision: HEAD
    path: ./Project1/config-files
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
